# Generated by Django 3.2 on 2023-10-31 05:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0010_auto_20231005_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(max_length=255)),
                ('Sku', models.CharField(max_length=255)),
                ('Team', models.CharField(max_length=255)),
                ('Vendor', models.CharField(max_length=255)),
                ('TotalBoard', models.IntegerField()),
                ('createdBy', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField()),
                ('modifiedBy', models.CharField(max_length=255)),
                ('modifiedDate', models.DateTimeField()),
                ('deletedBy', models.CharField(max_length=255)),
                ('deletedDate', models.DateTimeField()),
                ('isdeleted', models.BooleanField(default=False)),
                ('January', djongo.models.fields.JSONField()),
                ('February', djongo.models.fields.JSONField()),
                ('March', djongo.models.fields.JSONField()),
                ('April', djongo.models.fields.JSONField()),
                ('May', djongo.models.fields.JSONField()),
                ('June', djongo.models.fields.JSONField()),
                ('July', djongo.models.fields.JSONField()),
                ('August', djongo.models.fields.JSONField()),
                ('September', djongo.models.fields.JSONField()),
                ('October', djongo.models.fields.JSONField()),
                ('November', djongo.models.fields.JSONField()),
                ('December', djongo.models.fields.JSONField()),
            ],
        ),
    ]
