# Generated by Django 3.2 on 2023-11-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0012_auto_20231114_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardallocationdatamodel',
            name='year',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
    ]
