# Generated by Django 3.2 on 2024-01-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0014_utilizationmodel_utilizationsummarymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilizationModel',
        ),
    ]
