# Generated by Django 3.2 on 2024-01-22 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocationapp', '0015_delete_utilizationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardallocationdatamodel',
            name='operation_type',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='HistoricalBoardAllocationDataModel',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('Program', models.CharField(blank=True, max_length=100)),
                ('Sku', models.CharField(blank=True, max_length=100)),
                ('Team', models.CharField(blank=True, max_length=255)),
                ('Vendor', models.CharField(blank=True, max_length=255)),
                ('TotalBoard', models.IntegerField(default=0)),
                ('createdBy', models.CharField(blank=True, max_length=255)),
                ('createdDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255)),
                ('deletedDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('January', djongo.models.fields.JSONField()),
                ('February', djongo.models.fields.JSONField()),
                ('March', djongo.models.fields.JSONField()),
                ('April', djongo.models.fields.JSONField()),
                ('May', djongo.models.fields.JSONField()),
                ('June', djongo.models.fields.JSONField()),
                ('July', djongo.models.fields.JSONField()),
                ('August', djongo.models.fields.JSONField()),
                ('September', djongo.models.fields.JSONField()),
                ('October', djongo.models.fields.JSONField()),
                ('November', djongo.models.fields.JSONField()),
                ('December', djongo.models.fields.JSONField()),
                ('operation_type', models.CharField(blank=True, max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical board allocation data model',
                'verbose_name_plural': 'historical board allocation data models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
