# Generated by Django 3.2 on 2024-02-05 13:47

import allocationapp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0016_boardallocationdatamodeltrackdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocationdetailsmodel',
            old_name='DeallocatedBy',
            new_name='deallocatedBy',
        ),
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='RequestedBy',
            field=djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel, null=True),
        ),
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='RequestedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
