# Generated by Django 3.2 on 2024-03-05 10:47

import allocationapp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0017_auto_20240208_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Content', models.CharField(blank=True, max_length=100, null=True)),
                ('BroadCast_by', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel, null=True)),
                ('NewUser', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('User_mail_list', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilizationSummaryModelTrackData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_id', models.IntegerField()),
                ('workweek', models.CharField(blank=True, max_length=20)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('BenchData', models.CharField(max_length=255)),
                ('Program', models.CharField(blank=True, max_length=100)),
                ('Sku', models.CharField(blank=True, max_length=100)),
                ('Vendor', models.CharField(blank=True, max_length=100)),
                ('FromWW', models.CharField(blank=True, max_length=20)),
                ('ToWW', models.CharField(blank=True, max_length=20)),
                ('Duration', models.CharField(blank=True, max_length=10)),
                ('AllocatedTo', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel)),
                ('NumberOfbenches', models.IntegerField()),
                ('Remarks', models.TextField(blank=True)),
                ('Team', models.CharField(blank=True, max_length=100)),
                ('approvedBy', models.CharField(blank=True, max_length=255)),
                ('Planned_Utilization', models.FloatField(default=0)),
                ('Actual_Utilization', models.FloatField(default=0)),
                ('Actual_utilization_in_percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('Utilization_Percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('Allocated_POC', models.CharField(max_length=100)),
                ('Remarks_Utilization', models.CharField(blank=True, max_length=255)),
                ('Createdby', models.CharField(blank=True, max_length=255)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modifiedby', models.CharField(blank=True, max_length=255)),
                ('ModifiedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Deletedby', models.CharField(blank=True, max_length=255)),
                ('DeletedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
