# Generated by Django 3.2 on 2024-02-26 09:41

import allocationapp.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0018_broadcastmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmodel',
            name='NewUser',
            field=djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel, null=True),
        ),
    ]
